[package]
name = "snake"
version = "0.1.0"
authors = ["Marcin Witek <witek.marcin96@gmail.com>"]
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rusty_audio = "1.4.1"
rusty_time = "1.1.0"
rand = "0.9.0-alpha.2"